Minor fix on Windows (#56)
* Update synthesis.py

fix for error ,
TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, torch.cuda.IntTensor), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index)
on windows.
mentioned in the issue #37

* Added missing import hparams_debug_string